// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct CreateRequest: Hashable, CustomStringConvertible {
  /// 'file' | 'asset' | 'url'
  var sourceType: String
  var source: String
  /// 'none' | 'xorLegacy' | 'aesCtr' | 'clearKey' | custom adapter name
  var schemeType: String
  var schemeParams: [String?: Any?]
  /// 'texture' | 'platformView'
  var renderMode: String
  var autoPlay: Bool
  var looping: Bool
  var volume: Double
  var startPositionMs: Int64
  var minBufferMs: Int64
  var maxBufferMs: Int64
  var bufferForPlaybackMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateRequest? {
    let sourceType = pigeonVar_list[0] as! String
    let source = pigeonVar_list[1] as! String
    let schemeType = pigeonVar_list[2] as! String
    let schemeParams = pigeonVar_list[3] as! [String?: Any?]
    let renderMode = pigeonVar_list[4] as! String
    let autoPlay = pigeonVar_list[5] as! Bool
    let looping = pigeonVar_list[6] as! Bool
    let volume = pigeonVar_list[7] as! Double
    let startPositionMs = pigeonVar_list[8] as! Int64
    let minBufferMs = pigeonVar_list[9] as! Int64
    let maxBufferMs = pigeonVar_list[10] as! Int64
    let bufferForPlaybackMs = pigeonVar_list[11] as! Int64

    return CreateRequest(
      sourceType: sourceType,
      source: source,
      schemeType: schemeType,
      schemeParams: schemeParams,
      renderMode: renderMode,
      autoPlay: autoPlay,
      looping: looping,
      volume: volume,
      startPositionMs: startPositionMs,
      minBufferMs: minBufferMs,
      maxBufferMs: maxBufferMs,
      bufferForPlaybackMs: bufferForPlaybackMs
    )
  }
  func toList() -> [Any?] {
    return [
      sourceType,
      source,
      schemeType,
      schemeParams,
      renderMode,
      autoPlay,
      looping,
      volume,
      startPositionMs,
      minBufferMs,
      maxBufferMs,
      bufferForPlaybackMs,
    ]
  }
  static func == (lhs: CreateRequest, rhs: CreateRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sourceType, rhs.sourceType) && MessagesPigeonInternal.deepEquals(lhs.source, rhs.source) && MessagesPigeonInternal.deepEquals(lhs.schemeType, rhs.schemeType) && MessagesPigeonInternal.deepEquals(lhs.schemeParams, rhs.schemeParams) && MessagesPigeonInternal.deepEquals(lhs.renderMode, rhs.renderMode) && MessagesPigeonInternal.deepEquals(lhs.autoPlay, rhs.autoPlay) && MessagesPigeonInternal.deepEquals(lhs.looping, rhs.looping) && MessagesPigeonInternal.deepEquals(lhs.volume, rhs.volume) && MessagesPigeonInternal.deepEquals(lhs.startPositionMs, rhs.startPositionMs) && MessagesPigeonInternal.deepEquals(lhs.minBufferMs, rhs.minBufferMs) && MessagesPigeonInternal.deepEquals(lhs.maxBufferMs, rhs.maxBufferMs) && MessagesPigeonInternal.deepEquals(lhs.bufferForPlaybackMs, rhs.bufferForPlaybackMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreateRequest")
    MessagesPigeonInternal.deepHash(value: sourceType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemeType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemeParams, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: renderMode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: autoPlay, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: looping, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: volume, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startPositionMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minBufferMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxBufferMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bufferForPlaybackMs, hasher: &hasher)
  }

  public var description: String {
    return "CreateRequest(sourceType: \(String(describing: sourceType)), source: \(String(describing: source)), schemeType: \(String(describing: schemeType)), schemeParams: \(String(describing: schemeParams)), renderMode: \(String(describing: renderMode)), autoPlay: \(String(describing: autoPlay)), looping: \(String(describing: looping)), volume: \(String(describing: volume)), startPositionMs: \(String(describing: startPositionMs)), minBufferMs: \(String(describing: minBufferMs)), maxBufferMs: \(String(describing: maxBufferMs)), bufferForPlaybackMs: \(String(describing: bufferForPlaybackMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CreateResponse: Hashable, CustomStringConvertible {
  var playerId: Int64
  /// Null when renderMode == 'platformView'.
  var textureId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateResponse? {
    let playerId = pigeonVar_list[0] as! Int64
    let textureId: Int64? = nilOrValue(pigeonVar_list[1])

    return CreateResponse(
      playerId: playerId,
      textureId: textureId
    )
  }
  func toList() -> [Any?] {
    return [
      playerId,
      textureId,
    ]
  }
  static func == (lhs: CreateResponse, rhs: CreateResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.playerId, rhs.playerId) && MessagesPigeonInternal.deepEquals(lhs.textureId, rhs.textureId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreateResponse")
    MessagesPigeonInternal.deepHash(value: playerId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: textureId, hasher: &hasher)
  }

  public var description: String {
    return "CreateResponse(playerId: \(String(describing: playerId)), textureId: \(String(describing: textureId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TrackInfo: Hashable, CustomStringConvertible {
  var id: String
  /// 'audio' | 'subtitle' | 'video'
  var type: String
  var selected: Bool
  var label: String? = nil
  var language: String? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var bitrate: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackInfo? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let selected = pigeonVar_list[2] as! Bool
    let label: String? = nilOrValue(pigeonVar_list[3])
    let language: String? = nilOrValue(pigeonVar_list[4])
    let width: Int64? = nilOrValue(pigeonVar_list[5])
    let height: Int64? = nilOrValue(pigeonVar_list[6])
    let bitrate: Int64? = nilOrValue(pigeonVar_list[7])

    return TrackInfo(
      id: id,
      type: type,
      selected: selected,
      label: label,
      language: language,
      width: width,
      height: height,
      bitrate: bitrate
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      selected,
      label,
      language,
      width,
      height,
      bitrate,
    ]
  }
  static func == (lhs: TrackInfo, rhs: TrackInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.selected, rhs.selected) && MessagesPigeonInternal.deepEquals(lhs.label, rhs.label) && MessagesPigeonInternal.deepEquals(lhs.language, rhs.language) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.bitrate, rhs.bitrate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TrackInfo")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selected, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: language, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrate, hasher: &hasher)
  }

  public var description: String {
    return "TrackInfo(id: \(String(describing: id)), type: \(String(describing: type)), selected: \(String(describing: selected)), label: \(String(describing: label)), language: \(String(describing: language)), width: \(String(describing: width)), height: \(String(describing: height)), bitrate: \(String(describing: bitrate)))"
  }
}

/// One elementary stream inside a media container.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaStreamInfo: Hashable, CustomStringConvertible {
  /// 'video' | 'audio' | 'subtitle' | 'unknown'
  var type: String
  var codec: String? = nil
  var profile: String? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var frameRate: Double? = nil
  var bitrate: Int64? = nil
  var sampleRate: Int64? = nil
  var channels: Int64? = nil
  var language: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaStreamInfo? {
    let type = pigeonVar_list[0] as! String
    let codec: String? = nilOrValue(pigeonVar_list[1])
    let profile: String? = nilOrValue(pigeonVar_list[2])
    let width: Int64? = nilOrValue(pigeonVar_list[3])
    let height: Int64? = nilOrValue(pigeonVar_list[4])
    let frameRate: Double? = nilOrValue(pigeonVar_list[5])
    let bitrate: Int64? = nilOrValue(pigeonVar_list[6])
    let sampleRate: Int64? = nilOrValue(pigeonVar_list[7])
    let channels: Int64? = nilOrValue(pigeonVar_list[8])
    let language: String? = nilOrValue(pigeonVar_list[9])

    return MediaStreamInfo(
      type: type,
      codec: codec,
      profile: profile,
      width: width,
      height: height,
      frameRate: frameRate,
      bitrate: bitrate,
      sampleRate: sampleRate,
      channels: channels,
      language: language
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      codec,
      profile,
      width,
      height,
      frameRate,
      bitrate,
      sampleRate,
      channels,
      language,
    ]
  }
  static func == (lhs: MediaStreamInfo, rhs: MediaStreamInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.codec, rhs.codec) && MessagesPigeonInternal.deepEquals(lhs.profile, rhs.profile) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.frameRate, rhs.frameRate) && MessagesPigeonInternal.deepEquals(lhs.bitrate, rhs.bitrate) && MessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && MessagesPigeonInternal.deepEquals(lhs.channels, rhs.channels) && MessagesPigeonInternal.deepEquals(lhs.language, rhs.language)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaStreamInfo")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: profile, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: frameRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channels, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: language, hasher: &hasher)
  }

  public var description: String {
    return "MediaStreamInfo(type: \(String(describing: type)), codec: \(String(describing: codec)), profile: \(String(describing: profile)), width: \(String(describing: width)), height: \(String(describing: height)), frameRate: \(String(describing: frameRate)), bitrate: \(String(describing: bitrate)), sampleRate: \(String(describing: sampleRate)), channels: \(String(describing: channels)), language: \(String(describing: language)))"
  }
}

/// Container-level metadata + per-stream details (MX-Player-style info).
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfo: Hashable, CustomStringConvertible {
  var durationMs: Int64
  /// e.g. 'video/mp4' (Android MIME) or 'mp4' (iOS best effort).
  var container: String? = nil
  /// Display rotation in degrees (0/90/180/270) from the video track.
  var rotation: Int64? = nil
  /// Overall bitrate when the container reports one.
  var bitrate: Int64? = nil
  var streams: [MediaStreamInfo?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfo? {
    let durationMs = pigeonVar_list[0] as! Int64
    let container: String? = nilOrValue(pigeonVar_list[1])
    let rotation: Int64? = nilOrValue(pigeonVar_list[2])
    let bitrate: Int64? = nilOrValue(pigeonVar_list[3])
    let streams = pigeonVar_list[4] as! [MediaStreamInfo?]

    return MediaInfo(
      durationMs: durationMs,
      container: container,
      rotation: rotation,
      bitrate: bitrate,
      streams: streams
    )
  }
  func toList() -> [Any?] {
    return [
      durationMs,
      container,
      rotation,
      bitrate,
      streams,
    ]
  }
  static func == (lhs: MediaInfo, rhs: MediaInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.container, rhs.container) && MessagesPigeonInternal.deepEquals(lhs.rotation, rhs.rotation) && MessagesPigeonInternal.deepEquals(lhs.bitrate, rhs.bitrate) && MessagesPigeonInternal.deepEquals(lhs.streams, rhs.streams)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfo")
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: container, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: streams, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfo(durationMs: \(String(describing: durationMs)), container: \(String(describing: container)), rotation: \(String(describing: rotation)), bitrate: \(String(describing: bitrate)), streams: \(String(describing: streams)))"
  }
}

/// System media-controls surface (Android media notification via
/// MediaSessionService, iOS Now Playing + remote commands).
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaControlsConfig: Hashable, CustomStringConvertible {
  var enabled: Bool
  var title: String? = nil
  var artist: String? = nil
  /// Local file path to artwork image, optional.
  var artworkPath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaControlsConfig? {
    let enabled = pigeonVar_list[0] as! Bool
    let title: String? = nilOrValue(pigeonVar_list[1])
    let artist: String? = nilOrValue(pigeonVar_list[2])
    let artworkPath: String? = nilOrValue(pigeonVar_list[3])

    return MediaControlsConfig(
      enabled: enabled,
      title: title,
      artist: artist,
      artworkPath: artworkPath
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      title,
      artist,
      artworkPath,
    ]
  }
  static func == (lhs: MediaControlsConfig, rhs: MediaControlsConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.artist, rhs.artist) && MessagesPigeonInternal.deepEquals(lhs.artworkPath, rhs.artworkPath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaControlsConfig")
    MessagesPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: artist, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: artworkPath, hasher: &hasher)
  }

  public var description: String {
    return "MediaControlsConfig(enabled: \(String(describing: enabled)), title: \(String(describing: title)), artist: \(String(describing: artist)), artworkPath: \(String(describing: artworkPath)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CreateRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return CreateResponse.fromList(self.readValue() as! [Any?])
    case 131:
      return TrackInfo.fromList(self.readValue() as! [Any?])
    case 132:
      return MediaStreamInfo.fromList(self.readValue() as! [Any?])
    case 133:
      return MediaInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return MediaControlsConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CreateRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CreateResponse {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? TrackInfo {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MediaStreamInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MediaControlsConfig {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureVideoHostApi {
  func create(request: CreateRequest) throws -> CreateResponse
  func dispose(playerId: Int64) throws
  func play(playerId: Int64) throws
  func pause(playerId: Int64) throws
  func seekTo(playerId: Int64, positionMs: Int64) throws
  func setSpeed(playerId: Int64, speed: Double) throws
  func setLooping(playerId: Int64, looping: Bool) throws
  func setVolume(playerId: Int64, volume: Double) throws
  func getPosition(playerId: Int64) throws -> Int64
  func getTracks(playerId: Int64, type: String) throws -> [TrackInfo]
  /// trackId == null disables the track type (subtitles off / auto quality).
  func selectTrack(playerId: Int64, type: String, trackId: String?) throws
  func addExternalSubtitle(playerId: Int64, path: String, mimeType: String, language: String?) throws
  func enterPictureInPicture(playerId: Int64) throws -> Bool
  func setBackgroundPlayback(playerId: Int64, enabled: Bool) throws
  /// Window-level capture protection (FLAG_SECURE / iOS best effort).
  func setSecureFlag(enabled: Bool) throws
  /// Keeps the screen on while true (FLAG_KEEP_SCREEN_ON / isIdleTimerDisabled).
  /// Global window/app level — callers ref-count on the Dart side.
  func setKeepScreenAwake(enabled: Bool) throws
  /// Shows/updates (enabled=true) or tears down (enabled=false) system media
  /// controls for the player: Android media notification, iOS Now Playing.
  func configureMediaControls(playerId: Int64, config: MediaControlsConfig) throws
  /// Probes a (possibly encrypted) media file: container, duration, and
  /// per-stream codec/profile/resolution/fps/bitrate/sampleRate/channels.
  /// Decryption happens through the same CipherAdapter as playback.
  func getMediaInfo(path: String, schemeType: String, schemeParams: [String?: Any?]) throws -> MediaInfo
  /// Window screen brightness 0.0–1.0; pass -1 to restore system default.
  /// Android: WindowManager.LayoutParams.screenBrightness.
  /// iOS: UIScreen.main.brightness (persists — callers should restore).
  func setScreenBrightness(brightness: Double) throws
  /// Current window brightness 0.0–1.0 (-1 = following system default).
  func getScreenBrightness() throws -> Double
  /// Starts encrypt (encrypt=true) or decrypt file transform.
  /// Returns operationId; progress on EventChannel 'secure_video_player/crypto_events'.
  func startCrypto(inputPath: String, outputPath: String, schemeType: String, schemeParams: [String?: Any?], encrypt: Bool) throws -> String
  func cancelCrypto(operationId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureVideoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SecureVideoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureVideoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CreateRequest
        do {
          let result = try api.create(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.dispose(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.play(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.pause(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let positionMsArg = args[1] as! Int64
        do {
          try api.seekTo(playerId: playerIdArg, positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    let setSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let speedArg = args[1] as! Double
        do {
          try api.setSpeed(playerId: playerIdArg, speed: speedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSpeedChannel.setMessageHandler(nil)
    }
    let setLoopingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setLooping\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLoopingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let loopingArg = args[1] as! Bool
        do {
          try api.setLooping(playerId: playerIdArg, looping: loopingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLoopingChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let volumeArg = args[1] as! Double
        do {
          try api.setVolume(playerId: playerIdArg, volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    let getPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          let result = try api.getPosition(playerId: playerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPositionChannel.setMessageHandler(nil)
    }
    let getTracksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getTracks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTracksChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let typeArg = args[1] as! String
        do {
          let result = try api.getTracks(playerId: playerIdArg, type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTracksChannel.setMessageHandler(nil)
    }
    /// trackId == null disables the track type (subtitles off / auto quality).
    let selectTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.selectTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let typeArg = args[1] as! String
        let trackIdArg: String? = nilOrValue(args[2])
        do {
          try api.selectTrack(playerId: playerIdArg, type: typeArg, trackId: trackIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      selectTrackChannel.setMessageHandler(nil)
    }
    let addExternalSubtitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.addExternalSubtitle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addExternalSubtitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        let mimeTypeArg = args[2] as! String
        let languageArg: String? = nilOrValue(args[3])
        do {
          try api.addExternalSubtitle(playerId: playerIdArg, path: pathArg, mimeType: mimeTypeArg, language: languageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addExternalSubtitleChannel.setMessageHandler(nil)
    }
    let enterPictureInPictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.enterPictureInPicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enterPictureInPictureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          let result = try api.enterPictureInPicture(playerId: playerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enterPictureInPictureChannel.setMessageHandler(nil)
    }
    let setBackgroundPlaybackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setBackgroundPlayback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBackgroundPlaybackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        do {
          try api.setBackgroundPlayback(playerId: playerIdArg, enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBackgroundPlaybackChannel.setMessageHandler(nil)
    }
    /// Window-level capture protection (FLAG_SECURE / iOS best effort).
    let setSecureFlagChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setSecureFlag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSecureFlagChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setSecureFlag(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSecureFlagChannel.setMessageHandler(nil)
    }
    /// Keeps the screen on while true (FLAG_KEEP_SCREEN_ON / isIdleTimerDisabled).
    /// Global window/app level — callers ref-count on the Dart side.
    let setKeepScreenAwakeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setKeepScreenAwake\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setKeepScreenAwakeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setKeepScreenAwake(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setKeepScreenAwakeChannel.setMessageHandler(nil)
    }
    /// Shows/updates (enabled=true) or tears down (enabled=false) system media
    /// controls for the player: Android media notification, iOS Now Playing.
    let configureMediaControlsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.configureMediaControls\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureMediaControlsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let configArg = args[1] as! MediaControlsConfig
        do {
          try api.configureMediaControls(playerId: playerIdArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureMediaControlsChannel.setMessageHandler(nil)
    }
    /// Probes a (possibly encrypted) media file: container, duration, and
    /// per-stream codec/profile/resolution/fps/bitrate/sampleRate/channels.
    /// Decryption happens through the same CipherAdapter as playback.
    let getMediaInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getMediaInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let schemeTypeArg = args[1] as! String
        let schemeParamsArg = args[2] as! [String?: Any?]
        do {
          let result = try api.getMediaInfo(path: pathArg, schemeType: schemeTypeArg, schemeParams: schemeParamsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMediaInfoChannel.setMessageHandler(nil)
    }
    /// Window screen brightness 0.0–1.0; pass -1 to restore system default.
    /// Android: WindowManager.LayoutParams.screenBrightness.
    /// iOS: UIScreen.main.brightness (persists — callers should restore).
    let setScreenBrightnessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setScreenBrightness\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScreenBrightnessChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let brightnessArg = args[0] as! Double
        do {
          try api.setScreenBrightness(brightness: brightnessArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScreenBrightnessChannel.setMessageHandler(nil)
    }
    /// Current window brightness 0.0–1.0 (-1 = following system default).
    let getScreenBrightnessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getScreenBrightness\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScreenBrightnessChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getScreenBrightness()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getScreenBrightnessChannel.setMessageHandler(nil)
    }
    /// Starts encrypt (encrypt=true) or decrypt file transform.
    /// Returns operationId; progress on EventChannel 'secure_video_player/crypto_events'.
    let startCryptoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.startCrypto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCryptoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputPathArg = args[0] as! String
        let outputPathArg = args[1] as! String
        let schemeTypeArg = args[2] as! String
        let schemeParamsArg = args[3] as! [String?: Any?]
        let encryptArg = args[4] as! Bool
        do {
          let result = try api.startCrypto(inputPath: inputPathArg, outputPath: outputPathArg, schemeType: schemeTypeArg, schemeParams: schemeParamsArg, encrypt: encryptArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startCryptoChannel.setMessageHandler(nil)
    }
    let cancelCryptoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.cancelCrypto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelCryptoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let operationIdArg = args[0] as! String
        do {
          try api.cancelCrypto(operationId: operationIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelCryptoChannel.setMessageHandler(nil)
    }
  }
}
