// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.hulkenstein.secure_video_player

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateRequest (
  /** 'file' | 'asset' | 'url' */
  val sourceType: String,
  val source: String,
  /** 'none' | 'xorLegacy' | 'aesCtr' | 'clearKey' | custom adapter name */
  val schemeType: String,
  val schemeParams: Map<String?, Any?>,
  /** 'texture' | 'platformView' */
  val renderMode: String,
  val autoPlay: Boolean,
  val looping: Boolean,
  val volume: Double,
  val startPositionMs: Long,
  val minBufferMs: Long,
  val maxBufferMs: Long,
  val bufferForPlaybackMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateRequest {
      val sourceType = pigeonVar_list[0] as String
      val source = pigeonVar_list[1] as String
      val schemeType = pigeonVar_list[2] as String
      val schemeParams = pigeonVar_list[3] as Map<String?, Any?>
      val renderMode = pigeonVar_list[4] as String
      val autoPlay = pigeonVar_list[5] as Boolean
      val looping = pigeonVar_list[6] as Boolean
      val volume = pigeonVar_list[7] as Double
      val startPositionMs = pigeonVar_list[8] as Long
      val minBufferMs = pigeonVar_list[9] as Long
      val maxBufferMs = pigeonVar_list[10] as Long
      val bufferForPlaybackMs = pigeonVar_list[11] as Long
      return CreateRequest(sourceType, source, schemeType, schemeParams, renderMode, autoPlay, looping, volume, startPositionMs, minBufferMs, maxBufferMs, bufferForPlaybackMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceType,
      source,
      schemeType,
      schemeParams,
      renderMode,
      autoPlay,
      looping,
      volume,
      startPositionMs,
      minBufferMs,
      maxBufferMs,
      bufferForPlaybackMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreateRequest
    return MessagesPigeonUtils.deepEquals(this.sourceType, other.sourceType) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.schemeType, other.schemeType) && MessagesPigeonUtils.deepEquals(this.schemeParams, other.schemeParams) && MessagesPigeonUtils.deepEquals(this.renderMode, other.renderMode) && MessagesPigeonUtils.deepEquals(this.autoPlay, other.autoPlay) && MessagesPigeonUtils.deepEquals(this.looping, other.looping) && MessagesPigeonUtils.deepEquals(this.volume, other.volume) && MessagesPigeonUtils.deepEquals(this.startPositionMs, other.startPositionMs) && MessagesPigeonUtils.deepEquals(this.minBufferMs, other.minBufferMs) && MessagesPigeonUtils.deepEquals(this.maxBufferMs, other.maxBufferMs) && MessagesPigeonUtils.deepEquals(this.bufferForPlaybackMs, other.bufferForPlaybackMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.schemeType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.schemeParams)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.renderMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.autoPlay)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.looping)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.volume)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startPositionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.minBufferMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxBufferMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bufferForPlaybackMs)
    return result
  }
  override fun toString(): String {
    return "CreateRequest(sourceType=$sourceType, source=$source, schemeType=$schemeType, schemeParams=$schemeParams, renderMode=$renderMode, autoPlay=$autoPlay, looping=$looping, volume=$volume, startPositionMs=$startPositionMs, minBufferMs=$minBufferMs, maxBufferMs=$maxBufferMs, bufferForPlaybackMs=$bufferForPlaybackMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateResponse (
  val playerId: Long,
  /** Null when renderMode == 'platformView'. */
  val textureId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateResponse {
      val playerId = pigeonVar_list[0] as Long
      val textureId = pigeonVar_list[1] as Long?
      return CreateResponse(playerId, textureId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      textureId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreateResponse
    return MessagesPigeonUtils.deepEquals(this.playerId, other.playerId) && MessagesPigeonUtils.deepEquals(this.textureId, other.textureId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.playerId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.textureId)
    return result
  }
  override fun toString(): String {
    return "CreateResponse(playerId=$playerId, textureId=$textureId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrackInfo (
  val id: String,
  /** 'audio' | 'subtitle' | 'video' */
  val type: String,
  val selected: Boolean,
  val label: String? = null,
  val language: String? = null,
  val width: Long? = null,
  val height: Long? = null,
  val bitrate: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackInfo {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val selected = pigeonVar_list[2] as Boolean
      val label = pigeonVar_list[3] as String?
      val language = pigeonVar_list[4] as String?
      val width = pigeonVar_list[5] as Long?
      val height = pigeonVar_list[6] as Long?
      val bitrate = pigeonVar_list[7] as Long?
      return TrackInfo(id, type, selected, label, language, width, height, bitrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      selected,
      label,
      language,
      width,
      height,
      bitrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrackInfo
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.selected, other.selected) && MessagesPigeonUtils.deepEquals(this.label, other.label) && MessagesPigeonUtils.deepEquals(this.language, other.language) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.bitrate, other.bitrate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selected)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.label)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.language)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrate)
    return result
  }
  override fun toString(): String {
    return "TrackInfo(id=$id, type=$type, selected=$selected, label=$label, language=$language, width=$width, height=$height, bitrate=$bitrate)"
  }
}

/**
 * One elementary stream inside a media container.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaStreamInfo (
  /** 'video' | 'audio' | 'subtitle' | 'unknown' */
  val type: String,
  val codec: String? = null,
  val profile: String? = null,
  val width: Long? = null,
  val height: Long? = null,
  val frameRate: Double? = null,
  val bitrate: Long? = null,
  val sampleRate: Long? = null,
  val channels: Long? = null,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaStreamInfo {
      val type = pigeonVar_list[0] as String
      val codec = pigeonVar_list[1] as String?
      val profile = pigeonVar_list[2] as String?
      val width = pigeonVar_list[3] as Long?
      val height = pigeonVar_list[4] as Long?
      val frameRate = pigeonVar_list[5] as Double?
      val bitrate = pigeonVar_list[6] as Long?
      val sampleRate = pigeonVar_list[7] as Long?
      val channels = pigeonVar_list[8] as Long?
      val language = pigeonVar_list[9] as String?
      return MediaStreamInfo(type, codec, profile, width, height, frameRate, bitrate, sampleRate, channels, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      codec,
      profile,
      width,
      height,
      frameRate,
      bitrate,
      sampleRate,
      channels,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaStreamInfo
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.codec, other.codec) && MessagesPigeonUtils.deepEquals(this.profile, other.profile) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.frameRate, other.frameRate) && MessagesPigeonUtils.deepEquals(this.bitrate, other.bitrate) && MessagesPigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && MessagesPigeonUtils.deepEquals(this.channels, other.channels) && MessagesPigeonUtils.deepEquals(this.language, other.language)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.profile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.frameRate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.channels)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.language)
    return result
  }
  override fun toString(): String {
    return "MediaStreamInfo(type=$type, codec=$codec, profile=$profile, width=$width, height=$height, frameRate=$frameRate, bitrate=$bitrate, sampleRate=$sampleRate, channels=$channels, language=$language)"
  }
}

/**
 * Container-level metadata + per-stream details (MX-Player-style info).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaInfo (
  val durationMs: Long,
  /** e.g. 'video/mp4' (Android MIME) or 'mp4' (iOS best effort). */
  val container: String? = null,
  /** Display rotation in degrees (0/90/180/270) from the video track. */
  val rotation: Long? = null,
  /** Overall bitrate when the container reports one. */
  val bitrate: Long? = null,
  val streams: List<MediaStreamInfo?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfo {
      val durationMs = pigeonVar_list[0] as Long
      val container = pigeonVar_list[1] as String?
      val rotation = pigeonVar_list[2] as Long?
      val bitrate = pigeonVar_list[3] as Long?
      val streams = pigeonVar_list[4] as List<MediaStreamInfo?>
      return MediaInfo(durationMs, container, rotation, bitrate, streams)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMs,
      container,
      rotation,
      bitrate,
      streams,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfo
    return MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.container, other.container) && MessagesPigeonUtils.deepEquals(this.rotation, other.rotation) && MessagesPigeonUtils.deepEquals(this.bitrate, other.bitrate) && MessagesPigeonUtils.deepEquals(this.streams, other.streams)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.container)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.streams)
    return result
  }
  override fun toString(): String {
    return "MediaInfo(durationMs=$durationMs, container=$container, rotation=$rotation, bitrate=$bitrate, streams=$streams)"
  }
}

/**
 * System media-controls surface (Android media notification via
 * MediaSessionService, iOS Now Playing + remote commands).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaControlsConfig (
  val enabled: Boolean,
  val title: String? = null,
  val artist: String? = null,
  /** Local file path to artwork image, optional. */
  val artworkPath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaControlsConfig {
      val enabled = pigeonVar_list[0] as Boolean
      val title = pigeonVar_list[1] as String?
      val artist = pigeonVar_list[2] as String?
      val artworkPath = pigeonVar_list[3] as String?
      return MediaControlsConfig(enabled, title, artist, artworkPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      title,
      artist,
      artworkPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaControlsConfig
    return MessagesPigeonUtils.deepEquals(this.enabled, other.enabled) && MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.artist, other.artist) && MessagesPigeonUtils.deepEquals(this.artworkPath, other.artworkPath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.artist)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.artworkPath)
    return result
  }
  override fun toString(): String {
    return "MediaControlsConfig(enabled=$enabled, title=$title, artist=$artist, artworkPath=$artworkPath)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateResponse.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaStreamInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaControlsConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CreateRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CreateResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TrackInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MediaStreamInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MediaInfo -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaControlsConfig -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SecureVideoHostApi {
  fun create(request: CreateRequest): CreateResponse
  fun dispose(playerId: Long)
  fun play(playerId: Long)
  fun pause(playerId: Long)
  fun seekTo(playerId: Long, positionMs: Long)
  fun setSpeed(playerId: Long, speed: Double)
  fun setLooping(playerId: Long, looping: Boolean)
  fun setVolume(playerId: Long, volume: Double)
  fun getPosition(playerId: Long): Long
  fun getTracks(playerId: Long, type: String): List<TrackInfo>
  /** trackId == null disables the track type (subtitles off / auto quality). */
  fun selectTrack(playerId: Long, type: String, trackId: String?)
  fun addExternalSubtitle(playerId: Long, path: String, mimeType: String, language: String?)
  fun enterPictureInPicture(playerId: Long): Boolean
  fun setBackgroundPlayback(playerId: Long, enabled: Boolean)
  /** Window-level capture protection (FLAG_SECURE / iOS best effort). */
  fun setSecureFlag(enabled: Boolean)
  /**
   * Keeps the screen on while true (FLAG_KEEP_SCREEN_ON / isIdleTimerDisabled).
   * Global window/app level — callers ref-count on the Dart side.
   */
  fun setKeepScreenAwake(enabled: Boolean)
  /**
   * Shows/updates (enabled=true) or tears down (enabled=false) system media
   * controls for the player: Android media notification, iOS Now Playing.
   */
  fun configureMediaControls(playerId: Long, config: MediaControlsConfig)
  /**
   * Probes a (possibly encrypted) media file: container, duration, and
   * per-stream codec/profile/resolution/fps/bitrate/sampleRate/channels.
   * Decryption happens through the same CipherAdapter as playback.
   *
   * Runs on a background task queue so the blocking probe never stalls the
   * platform thread (ANR on slow storage / native schemes).
   */
  fun getMediaInfo(path: String, schemeType: String, schemeParams: Map<String?, Any?>): MediaInfo
  /**
   * Window screen brightness 0.0–1.0; pass -1 to restore system default.
   * Android: WindowManager.LayoutParams.screenBrightness.
   * iOS: UIScreen.main.brightness (persists — callers should restore).
   */
  fun setScreenBrightness(brightness: Double)
  /** Current window brightness 0.0–1.0 (-1 = following system default). */
  fun getScreenBrightness(): Double
  /**
   * Starts encrypt (encrypt=true) or decrypt file transform.
   * Returns operationId; progress on EventChannel 'secure_video_player/crypto_events'.
   */
  fun startCrypto(inputPath: String, outputPath: String, schemeType: String, schemeParams: Map<String?, Any?>, encrypt: Boolean): String
  fun cancelCrypto(operationId: String)

  companion object {
    /** The codec used by SecureVideoHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SecureVideoHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecureVideoHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CreateRequest
            val wrapped: List<Any?> = try {
              listOf(api.create(requestArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.dispose(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.play(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pause(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val positionMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.seekTo(playerIdArg, positionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val speedArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setSpeed(playerIdArg, speedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setLooping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val loopingArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setLooping(playerIdArg, loopingArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val volumeArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setVolume(playerIdArg, volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getPosition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getPosition(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getTracks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val typeArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.getTracks(playerIdArg, typeArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.selectTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val typeArg = args[1] as String
            val trackIdArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.selectTrack(playerIdArg, typeArg, trackIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.addExternalSubtitle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val pathArg = args[1] as String
            val mimeTypeArg = args[2] as String
            val languageArg = args[3] as String?
            val wrapped: List<Any?> = try {
              api.addExternalSubtitle(playerIdArg, pathArg, mimeTypeArg, languageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.enterPictureInPicture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.enterPictureInPicture(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setBackgroundPlayback$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val enabledArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setBackgroundPlayback(playerIdArg, enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setSecureFlag$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setSecureFlag(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setKeepScreenAwake$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setKeepScreenAwake(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.configureMediaControls$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val configArg = args[1] as MediaControlsConfig
            val wrapped: List<Any?> = try {
              api.configureMediaControls(playerIdArg, configArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getMediaInfo$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val schemeTypeArg = args[1] as String
            val schemeParamsArg = args[2] as Map<String?, Any?>
            val wrapped: List<Any?> = try {
              listOf(api.getMediaInfo(pathArg, schemeTypeArg, schemeParamsArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setScreenBrightness$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val brightnessArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setScreenBrightness(brightnessArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getScreenBrightness$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getScreenBrightness())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.startCrypto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputPathArg = args[0] as String
            val outputPathArg = args[1] as String
            val schemeTypeArg = args[2] as String
            val schemeParamsArg = args[3] as Map<String?, Any?>
            val encryptArg = args[4] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.startCrypto(inputPathArg, outputPathArg, schemeTypeArg, schemeParamsArg, encryptArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.cancelCrypto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val operationIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelCrypto(operationIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
