// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class CreateRequest {
  CreateRequest({
    required this.sourceType,
    required this.source,
    required this.schemeType,
    required this.schemeParams,
    required this.renderMode,
    required this.autoPlay,
    required this.looping,
    required this.volume,
    required this.startPositionMs,
    required this.minBufferMs,
    required this.maxBufferMs,
    required this.bufferForPlaybackMs,
  });

  /// 'file' | 'asset' | 'url'
  String sourceType;

  String source;

  /// 'none' | 'xorLegacy' | 'aesCtr' | 'clearKey' | custom adapter name
  String schemeType;

  Map<String?, Object?> schemeParams;

  /// 'texture' | 'platformView'
  String renderMode;

  bool autoPlay;

  bool looping;

  double volume;

  int startPositionMs;

  int minBufferMs;

  int maxBufferMs;

  int bufferForPlaybackMs;

  List<Object?> _toList() {
    return <Object?>[
      sourceType,
      source,
      schemeType,
      schemeParams,
      renderMode,
      autoPlay,
      looping,
      volume,
      startPositionMs,
      minBufferMs,
      maxBufferMs,
      bufferForPlaybackMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static CreateRequest decode(Object result) {
    result as List<Object?>;
    return CreateRequest(
      sourceType: result[0]! as String,
      source: result[1]! as String,
      schemeType: result[2]! as String,
      schemeParams: (result[3]! as Map<Object?, Object?>).cast<String?, Object?>(),
      renderMode: result[4]! as String,
      autoPlay: result[5]! as bool,
      looping: result[6]! as bool,
      volume: result[7]! as double,
      startPositionMs: result[8]! as int,
      minBufferMs: result[9]! as int,
      maxBufferMs: result[10]! as int,
      bufferForPlaybackMs: result[11]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceType, other.sourceType) && _deepEquals(source, other.source) && _deepEquals(schemeType, other.schemeType) && _deepEquals(schemeParams, other.schemeParams) && _deepEquals(renderMode, other.renderMode) && _deepEquals(autoPlay, other.autoPlay) && _deepEquals(looping, other.looping) && _deepEquals(volume, other.volume) && _deepEquals(startPositionMs, other.startPositionMs) && _deepEquals(minBufferMs, other.minBufferMs) && _deepEquals(maxBufferMs, other.maxBufferMs) && _deepEquals(bufferForPlaybackMs, other.bufferForPlaybackMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CreateRequest(sourceType: $sourceType, source: $source, schemeType: $schemeType, schemeParams: $schemeParams, renderMode: $renderMode, autoPlay: $autoPlay, looping: $looping, volume: $volume, startPositionMs: $startPositionMs, minBufferMs: $minBufferMs, maxBufferMs: $maxBufferMs, bufferForPlaybackMs: $bufferForPlaybackMs)';
  }
}

class CreateResponse {
  CreateResponse({
    required this.playerId,
    this.textureId,
  });

  int playerId;

  /// Null when renderMode == 'platformView'.
  int? textureId;

  List<Object?> _toList() {
    return <Object?>[
      playerId,
      textureId,
    ];
  }

  Object encode() {
    return _toList();  }

  static CreateResponse decode(Object result) {
    result as List<Object?>;
    return CreateResponse(
      playerId: result[0]! as int,
      textureId: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(playerId, other.playerId) && _deepEquals(textureId, other.textureId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CreateResponse(playerId: $playerId, textureId: $textureId)';
  }
}

class TrackInfo {
  TrackInfo({
    required this.id,
    required this.type,
    required this.selected,
    this.label,
    this.language,
    this.width,
    this.height,
    this.bitrate,
  });

  String id;

  /// 'audio' | 'subtitle' | 'video'
  String type;

  bool selected;

  String? label;

  String? language;

  int? width;

  int? height;

  int? bitrate;

  List<Object?> _toList() {
    return <Object?>[
      id,
      type,
      selected,
      label,
      language,
      width,
      height,
      bitrate,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrackInfo decode(Object result) {
    result as List<Object?>;
    return TrackInfo(
      id: result[0]! as String,
      type: result[1]! as String,
      selected: result[2]! as bool,
      label: result[3] as String?,
      language: result[4] as String?,
      width: result[5] as int?,
      height: result[6] as int?,
      bitrate: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(selected, other.selected) && _deepEquals(label, other.label) && _deepEquals(language, other.language) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(bitrate, other.bitrate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrackInfo(id: $id, type: $type, selected: $selected, label: $label, language: $language, width: $width, height: $height, bitrate: $bitrate)';
  }
}

/// One elementary stream inside a media container.
class MediaStreamInfo {
  MediaStreamInfo({
    required this.type,
    this.codec,
    this.profile,
    this.width,
    this.height,
    this.frameRate,
    this.bitrate,
    this.sampleRate,
    this.channels,
    this.language,
  });

  /// 'video' | 'audio' | 'subtitle' | 'unknown'
  String type;

  String? codec;

  String? profile;

  int? width;

  int? height;

  double? frameRate;

  int? bitrate;

  int? sampleRate;

  int? channels;

  String? language;

  List<Object?> _toList() {
    return <Object?>[
      type,
      codec,
      profile,
      width,
      height,
      frameRate,
      bitrate,
      sampleRate,
      channels,
      language,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaStreamInfo decode(Object result) {
    result as List<Object?>;
    return MediaStreamInfo(
      type: result[0]! as String,
      codec: result[1] as String?,
      profile: result[2] as String?,
      width: result[3] as int?,
      height: result[4] as int?,
      frameRate: result[5] as double?,
      bitrate: result[6] as int?,
      sampleRate: result[7] as int?,
      channels: result[8] as int?,
      language: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaStreamInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(codec, other.codec) && _deepEquals(profile, other.profile) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(frameRate, other.frameRate) && _deepEquals(bitrate, other.bitrate) && _deepEquals(sampleRate, other.sampleRate) && _deepEquals(channels, other.channels) && _deepEquals(language, other.language);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaStreamInfo(type: $type, codec: $codec, profile: $profile, width: $width, height: $height, frameRate: $frameRate, bitrate: $bitrate, sampleRate: $sampleRate, channels: $channels, language: $language)';
  }
}

/// Container-level metadata + per-stream details (MX-Player-style info).
class MediaInfo {
  MediaInfo({
    required this.durationMs,
    this.container,
    this.rotation,
    this.bitrate,
    required this.streams,
  });

  int durationMs;

  /// e.g. 'video/mp4' (Android MIME) or 'mp4' (iOS best effort).
  String? container;

  /// Display rotation in degrees (0/90/180/270) from the video track.
  int? rotation;

  /// Overall bitrate when the container reports one.
  int? bitrate;

  List<MediaStreamInfo?> streams;

  List<Object?> _toList() {
    return <Object?>[
      durationMs,
      container,
      rotation,
      bitrate,
      streams,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaInfo decode(Object result) {
    result as List<Object?>;
    return MediaInfo(
      durationMs: result[0]! as int,
      container: result[1] as String?,
      rotation: result[2] as int?,
      bitrate: result[3] as int?,
      streams: (result[4]! as List<Object?>).cast<MediaStreamInfo?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(durationMs, other.durationMs) && _deepEquals(container, other.container) && _deepEquals(rotation, other.rotation) && _deepEquals(bitrate, other.bitrate) && _deepEquals(streams, other.streams);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaInfo(durationMs: $durationMs, container: $container, rotation: $rotation, bitrate: $bitrate, streams: $streams)';
  }
}

/// System media-controls surface (Android media notification via
/// MediaSessionService, iOS Now Playing + remote commands).
class MediaControlsConfig {
  MediaControlsConfig({
    required this.enabled,
    this.title,
    this.artist,
    this.artworkPath,
  });

  bool enabled;

  String? title;

  String? artist;

  /// Local file path to artwork image, optional.
  String? artworkPath;

  List<Object?> _toList() {
    return <Object?>[
      enabled,
      title,
      artist,
      artworkPath,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaControlsConfig decode(Object result) {
    result as List<Object?>;
    return MediaControlsConfig(
      enabled: result[0]! as bool,
      title: result[1] as String?,
      artist: result[2] as String?,
      artworkPath: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaControlsConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(enabled, other.enabled) && _deepEquals(title, other.title) && _deepEquals(artist, other.artist) && _deepEquals(artworkPath, other.artworkPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaControlsConfig(enabled: $enabled, title: $title, artist: $artist, artworkPath: $artworkPath)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CreateRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is CreateResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TrackInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is MediaStreamInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MediaInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is MediaControlsConfig) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CreateRequest.decode(readValue(buffer)!);
      case 130:
        return CreateResponse.decode(readValue(buffer)!);
      case 131:
        return TrackInfo.decode(readValue(buffer)!);
      case 132:
        return MediaStreamInfo.decode(readValue(buffer)!);
      case 133:
        return MediaInfo.decode(readValue(buffer)!);
      case 134:
        return MediaControlsConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SecureVideoHostApi {
  /// Constructor for [SecureVideoHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SecureVideoHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CreateResponse> create(CreateRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CreateResponse;
  }

  Future<void> dispose(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> play(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pause(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekTo(int playerId, int positionMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.seekTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, positionMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setSpeed(int playerId, double speed) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setSpeed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, speed]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setLooping(int playerId, bool looping) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setLooping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, looping]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVolume(int playerId, double volume) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, volume]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> getPosition(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getPosition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<List<TrackInfo>> getTracks(int playerId, String type) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getTracks$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, type]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<TrackInfo>();
  }

  /// trackId == null disables the track type (subtitles off / auto quality).
  Future<void> selectTrack(int playerId, String type, String? trackId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.selectTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, type, trackId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> addExternalSubtitle(int playerId, String path, String mimeType, String? language) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.addExternalSubtitle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, path, mimeType, language]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> enterPictureInPicture(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.enterPictureInPicture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setBackgroundPlayback(int playerId, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setBackgroundPlayback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Window-level capture protection (FLAG_SECURE / iOS best effort).
  Future<void> setSecureFlag(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setSecureFlag$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Keeps the screen on while true (FLAG_KEEP_SCREEN_ON / isIdleTimerDisabled).
  /// Global window/app level — callers ref-count on the Dart side.
  Future<void> setKeepScreenAwake(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setKeepScreenAwake$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Shows/updates (enabled=true) or tears down (enabled=false) system media
  /// controls for the player: Android media notification, iOS Now Playing.
  Future<void> configureMediaControls(int playerId, MediaControlsConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.configureMediaControls$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Probes a (possibly encrypted) media file: container, duration, and
  /// per-stream codec/profile/resolution/fps/bitrate/sampleRate/channels.
  /// Decryption happens through the same CipherAdapter as playback.
  ///
  /// Runs on a background task queue so the blocking probe never stalls the
  /// platform thread (ANR on slow storage / native schemes).
  Future<MediaInfo> getMediaInfo(String path, String schemeType, Map<String?, Object?> schemeParams) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getMediaInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, schemeType, schemeParams]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaInfo;
  }

  /// Window screen brightness 0.0–1.0; pass -1 to restore system default.
  /// Android: WindowManager.LayoutParams.screenBrightness.
  /// iOS: UIScreen.main.brightness (persists — callers should restore).
  Future<void> setScreenBrightness(double brightness) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.setScreenBrightness$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[brightness]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Current window brightness 0.0–1.0 (-1 = following system default).
  Future<double> getScreenBrightness() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.getScreenBrightness$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as double;
  }

  /// Starts encrypt (encrypt=true) or decrypt file transform.
  /// Returns operationId; progress on EventChannel 'secure_video_player/crypto_events'.
  Future<String> startCrypto(String inputPath, String outputPath, String schemeType, Map<String?, Object?> schemeParams, bool encrypt) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.startCrypto$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[inputPath, outputPath, schemeType, schemeParams, encrypt]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> cancelCrypto(String operationId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.secure_video_player.SecureVideoHostApi.cancelCrypto$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[operationId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
